version: '2'

networks:
  app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  mysqldb:
    image: mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_USER=springuser
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_PASSWORD=ThePassword
     - MYSQL_DATABASE=db_example
     - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
     - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      app-tier:
        ipv4_address: 172.18.0.5

  bootmysql:
    image: springboot-mysql/gs-mysql-data
    ports:
     - "80:9077"
    networks:
      app-tier:
        ipv4_address: 172.18.0.6
    depends_on:
     - mysqldb